version: '3.1'

services:
    node-red:
        build:
            context: .
            dockerfile: Dockerfile
        # command: ./node_modules/.bin/nodemon --watch /data/.node-red/nodes/ha-eventer --exec node --inspect red.js
        volumes:
            - $PWD:/data/.node-red/nodes/ha-eventer
            - $PWD/settings.js:/data/.node-red/settings.js:ro
            # - node-red-data:/data
            # - node-red-app:/app
        ports:
            - 1880:1880
            - 9229:9229

volumes:
    node-red-data:
    node-red-app:
