homeassistant:
  name:             Home
  latitude:         !env_var HA_HOME_ASSISTANT_LATITUDE
  longitude:        !env_var HA_HOME_ASSISTANT_LONGITUDE
  elevation:        !env_var HA_HOME_ASSISTANT_ELEVATION
  temperature_unit: !env_var HA_HOME_ASSISTANT_TEMPERATURE_UNIT
  time_zone:        !env_var HA_HOME_ASSISTANT_TIME_ZONE
  unit_system:      !env_var HA_HOME_ASSISTANT_UNIT_SYSTEM

http:
  api_password: !env_var HA_HTTP_API_PASSWORD

logger:
  default: !env_var HA_LOGGER_DEFAULT

recorder:
logbook:
frontend:
config:
history:
map:
sun:

panel_iframe:
  node_red:
    title: Node Red
    url:   !env_var NODE_RED_URL
    icon:  mdi:sitemap


alarm_control_panel:
  - platform: demo

binary_sensor:
  - platform: demo

camera:
  - platform: demo

climate:
  - platform: demo

cover:
  - platform: demo

fan:
  - platform: demo

image_processing:
  - platform: demo

light:
  - platform: demo

lock:
  - platform: demo

notify:
  - platform: demo

remote:
  - platform: demo

sensor:
  - platform: demo

switch:
  - platform: demo

tts:
  - platform: demo

weather:
  - platform: demo

mailbox:
  - platform: demo

input_select:
  time_of_day:
    name: Time of Day
    options:
     - Morning
     - Afternoon
     - Evening
     - Party Time
    initial: Morning
    icon: mdi:schedule

input_number:
  global_light_level:
    name: Global Light Level
    initial: 10
    min: 1
    max: 100
    step: 5

input_boolean:
  notify_home:
    name: Use Global Light Level
    initial: off
    icon: mdi:lightbulb_outline

input_datetime:
  only_date:
    name: Input with only date
    has_date: true
    has_time: false
  only_time:
    name: Input with only time
    has_date: false
    has_time: true

# Test Entities for Development
# automation:
#   initial_state: True
#   trigger:
#     platform: time
#     seconds: '/10'
#   action:
#     service: switch.toggle
#     entity_id: light.kitchen_light
